version: '3.8'

services:
  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  ceres_medicoes_info:
    build:
      context: .
      dockerfile: Dockerfile.ceres_medicoes_info
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  ceres_medicoes_historico:
    build:
      context: .
      dockerfile: Dockerfile.ceres_medicoes_historico
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
