# Dockerfile for insert_ceres_medicoes_info.py
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY insert_ceres_medicoes_info.py .

CMD ["python", "insert_ceres_medicoes_info.py"]
